using zincstd;

string word = "abcdefghijklmnopqrstuvwxyz";

word_list{word.length()};

main(){
    loop(word.length(), a){
        word_list[a] = word[a];
    }

    loop(word.size(), i){
        loop(i, j){
            print(word_list[abs(i-word.length())]);
        }
        print(" ");
        loop(abs(i-word.size()), k){
            print(word_list[k]);
        }
        newline();
    }

    delete[] word_list;
}
