using zincstd;

string word = "abcdefghijklmnopqrstuvwxyz";

char* word_list = new char[word.length()];

main(){
    loop(word.length(), a){
        word_list[a] = word[a];
    }

    loop(word.size(), i){
        loop(i, j){
            print(word_list[j]);
        }
        print(" ");
        loop(abs(i-word.size()), k){
            print(word_list[k]);
        }
        newline();
    }

    // Don't forget to release the allocated memory when done
    delete[] word_list;
}
