using zincstd;

string word = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890!@#$%^&*()";

string word_list[100];

main(){
    loop(word.length(), a){
        word_list[a] = word[a];
    }

    loop(word.size(), i){
        loop(i, j){
            print(word_list[abs(j-word.length())]);
        }
        print(" ");
        loop(abs(i-word.size()), k){
            print(word_list[k]);
        }
        newline();
    }
}
